/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Health check
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The service is healthy */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["401"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List running sandboxes
         * @deprecated
         * @description List all running sandboxes. Use GET /v2/sandboxes instead.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Metadata query used to filter the sandboxes (e.g. "user=abc&app=prod"). Each key and values must be URL encoded. */
                    metadata?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned all running sandboxes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListedSandbox"][];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        /**
         * Create sandbox
         * @deprecated
         * @description Create a sandbox from an existing template/snapshot. Use POST /v2/sandboxes instead or POST /sandboxes-cold to create a sandbox directly from an external OCI image.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewSandbox"];
                };
            };
            responses: {
                /** @description The sandbox was created successfully */
                201: {
                    headers: {
                        /** @description Identifier of the created sandbox for proxy routing. */
                        "x-agentenv-sandbox-id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sandbox"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                409: components["responses"]["409"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes-cold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a sandbox directly from an explicit external OCI image reference. Cold starts may pull and convert OCI layers on a cache miss and can take tens of seconds; clients should use a long HTTP timeout for this path. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewColdSandbox"];
                };
            };
            responses: {
                /** @description The sandbox was created successfully */
                201: {
                    headers: {
                        /** @description Identifier of the created sandbox for proxy routing. */
                        "x-agentenv-sandbox-id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sandbox"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                409: components["responses"]["409"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{templateID}/builds/{buildID}/builder": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateID: string;
                buildID: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Prepare the BuildKit worker for a template build
         * @description Start a BuildKit worker for the template build
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    templateID: string;
                    buildID: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TemplateBuilderRequest"];
                };
            };
            responses: {
                /** @description Builder preparation accepted */
                202: {
                    headers: {
                        /** @description Build identifier used by the gateway for routing. */
                        "x-agentenv-build-id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TemplateBuilder"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                409: components["responses"]["409"];
                /** @description Concurrent build limit reached */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["500"];
            };
        };
        post?: never;
        /**
         * Cancel a template build and release its worker
         * @description Cancel the build and release its BuildKit worker
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    templateID: string;
                    buildID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Builder released */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                409: components["responses"]["409"];
                500: components["responses"]["500"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/sandboxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sandboxes (v2)
         * @description List all sandboxes
         */
        get: {
            parameters: {
                query?: {
                    /** @description Metadata query used to filter the sandboxes (e.g. "user=abc&app=prod"). Each key and values must be URL encoded. */
                    metadata?: string;
                    /** @description Filter sandboxes by one or more states */
                    state?: components["schemas"]["SandboxState"][];
                    /** @description Sort direction by sandbox start time. Defaults to desc (newest first). */
                    order?: components["schemas"]["OrderDirection"];
                    /** @description Return sandboxes started at or after this timestamp. */
                    startedAfter?: string;
                    /** @description Filter sandboxes by a template ID or alias. */
                    template?: string;
                    /** @description Cursor to start the list from */
                    nextToken?: components["parameters"]["paginationNextToken"];
                    /** @description Maximum number of items to return per page */
                    limit?: components["parameters"]["paginationLimit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned all running sandboxes */
                200: {
                    headers: {
                        "X-Next-Token": components["headers"]["XNextToken"];
                        "X-Total-Running": components["headers"]["XTotalRunning"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListedSandbox"][];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        /**
         * Create sandbox (v2)
         * @description Create a sandbox from the template. All system communication with the sandbox is secured.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewSandboxV2"];
                };
            };
            responses: {
                /** @description The sandbox was created successfully */
                201: {
                    headers: {
                        /** @description Identifier of the created sandbox for proxy routing. */
                        "x-agentenv-sandbox-id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sandbox"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                409: components["responses"]["409"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sandbox metrics
         * @description Latest fresh samples for requested running sandboxes. Missing, paused, or unavailable sandboxes are omitted.
         */
        get: {
            parameters: {
                query: {
                    /** @description Comma-separated sandbox IDs. */
                    sandbox_ids: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned all running sandboxes with metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SandboxesWithMetrics"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{sandboxID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sandbox
         * @description Get a sandbox by id
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sandboxID: components["parameters"]["sandboxID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned the sandbox */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SandboxDetail"];
                    };
                };
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Kill sandbox
         * @description Kill a sandbox
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sandboxID: components["parameters"]["sandboxID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The sandbox was killed successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                500: components["responses"]["500"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{sandboxID}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sandbox metrics
         * @description Samples in the inclusive start/end interval, in ascending time order. Defaults to all retained samples. History is node-local, bounded, and lost on restart.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Unix timestamp in seconds, inclusive. */
                    start?: number;
                    /** @description Unix timestamp in seconds, inclusive. */
                    end?: number;
                };
                header?: never;
                path: {
                    sandboxID: components["parameters"]["sandboxID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned the sandbox metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SandboxMetric"][];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{sandboxID}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause sandbox
         * @description Pause the sandbox
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sandboxID: components["parameters"]["sandboxID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The sandbox was paused successfully and can be resumed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                409: components["responses"]["409"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{sandboxID}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume sandbox
         * @deprecated
         * @description Resume the sandbox
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sandboxID: components["parameters"]["sandboxID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResumedSandbox"];
                };
            };
            responses: {
                /** @description The sandbox was resumed successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sandbox"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                409: components["responses"]["409"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{sandboxID}/fork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fork sandbox
         * @description Fork the sandbox: checkpoint the running sandbox in place (it is briefly paused, snapshotted with its full memory state, and resumed on its node, keeping its ID and expiration untouched) and create count new sandboxes from that snapshot. Returns one result per requested fork, each carrying either the created sandbox or the error that prevented it from starting. A non-201 status means the request failed before any fork was attempted.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sandboxID: components["parameters"]["sandboxID"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SandboxForkRequest"];
                };
            };
            responses: {
                /** @description The sandbox was snapshotted and the forks were attempted; each entry reports one fork's outcome */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SandboxForkResult"][];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                409: components["responses"]["409"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{sandboxID}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect sandbox
         * @deprecated
         * @description Returns sandbox details. If the sandbox is paused, it will be resumed. TTL is only extended. Use POST /v2/sandboxes/{sandboxID}/connect instead.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sandboxID: components["parameters"]["sandboxID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConnectSandbox"];
                };
            };
            responses: {
                /** @description The sandbox was already running */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sandbox"];
                    };
                };
                /** @description The sandbox was resumed successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sandbox"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                409: components["responses"]["409"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/sandboxes/{sandboxID}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect sandbox (v2)
         * @description Returns sandbox details. If the sandbox is paused, it will be resumed. TTL is only extended. The request body is optional; an omitted timeout defaults to 300 seconds.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sandboxID: components["parameters"]["sandboxID"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ConnectSandboxV2"];
                };
            };
            responses: {
                /** @description The sandbox was already running */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sandbox"];
                    };
                };
                /** @description The sandbox was resumed successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sandbox"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                409: components["responses"]["409"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{sandboxID}/timeout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set sandbox timeout
         * @description Set the timeout for the sandbox. The sandbox will expire x seconds from the time of the request. Calling this method multiple times overwrites the TTL, each time using the current timestamp as the starting point to measure the timeout duration.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sandboxID: components["parameters"]["sandboxID"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SandboxTimeoutRequest"];
                };
            };
            responses: {
                /** @description Successfully set the sandbox timeout */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{sandboxID}/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update sandbox network
         * @description Update the network configuration for a running sandbox. Replaces the current egress rules with the provided configuration. Omitting field clears it.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sandboxID: components["parameters"]["sandboxID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SandboxNetworkUpdateConfig"];
                };
            };
            responses: {
                /** @description Successfully updated the sandbox network configuration */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                409: components["responses"]["409"];
                500: components["responses"]["500"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{sandboxID}/custom-extension-params": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the current custom extension params of the sandbox. Returns an empty object when no params are set. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sandboxID: components["parameters"]["sandboxID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The current custom extension params */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomExtensionParams"];
                    };
                };
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Patch the custom extension params of a running sandbox. The request body is passed through verbatim to the custom extension's patch-params hook, whose semantics are defined entirely by the extension. The hook returns the updated full params, which become the sandbox's new current params and are returned by this call. Requires the custom extension to be configured on the server. Concurrent patches to the same sandbox are not serialized; non-commutative patch semantics must be handled by the extension. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sandboxID: components["parameters"]["sandboxID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description The updated full custom extension params */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomExtensionParams"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                409: components["responses"]["409"];
                500: components["responses"]["500"];
            };
        };
        trace?: never;
    };
    "/sandboxes/{sandboxID}/refreshes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh sandbox
         * @description Refresh the sandbox extending its time to live
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sandboxID: components["parameters"]["sandboxID"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SandboxRefreshRequest"];
                };
            };
            responses: {
                /** @description Successfully refreshed the sandbox */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{sandboxID}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create snapshot
         * @description Create a persistent snapshot from the sandbox's current state. Snapshots can be used to create new sandboxes and persist beyond the original sandbox's lifetime.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sandboxID: components["parameters"]["sandboxID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SandboxSnapshotRequest"];
                };
            };
            responses: {
                /** @description Snapshot created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SnapshotInfo"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List snapshots
         * @description List all snapshots for the team
         */
        get: {
            parameters: {
                query?: {
                    sandboxID?: string;
                    /** @description Filter snapshots by name or ID, optionally tag-qualified (e.g. "my-snapshot", "my-team/my-snapshot" or "my-snapshot:v1"). */
                    name?: string;
                    /** @description Maximum number of items to return per page */
                    limit?: components["parameters"]["paginationLimit"];
                    /** @description Cursor to start the list from */
                    nextToken?: components["parameters"]["paginationNextToken"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned snapshots */
                200: {
                    headers: {
                        "X-Next-Token": components["headers"]["XNextToken"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SnapshotInfo"][];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshotID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get information about a single snapshot by its ID or alias */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    snapshotID: components["parameters"]["snapshotID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned the snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SnapshotInfo"];
                    };
                };
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create template (v3)
         * @description Create a new template
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TemplateBuildRequestV3"];
                };
            };
            responses: {
                /** @description The build was requested successfully */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TemplateRequestResponseV3"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List templates (v2)
         * @description List all templates
         */
        get: {
            parameters: {
                query?: {
                    teamID?: string;
                    /** @description Cursor to start the list from */
                    nextToken?: components["parameters"]["paginationNextToken"];
                    /** @description Maximum number of items to return per page */
                    limit?: components["parameters"]["paginationLimit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned all templates */
                200: {
                    headers: {
                        "X-Next-Token": components["headers"]["XNextToken"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Template"][];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                403: components["responses"]["403"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List templates
         * @deprecated
         * @description List all templates
         */
        get: {
            parameters: {
                query?: {
                    teamID?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned all templates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Template"][];
                    };
                };
                401: components["responses"]["401"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{templateID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List template builds
         * @description List all builds for a template
         */
        get: {
            parameters: {
                query?: {
                    /** @description Cursor to start the list from */
                    nextToken?: components["parameters"]["paginationNextToken"];
                    /** @description Maximum number of items to return per page */
                    limit?: components["parameters"]["paginationLimit"];
                };
                header?: never;
                path: {
                    templateID: components["parameters"]["templateID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned the template with its builds */
                200: {
                    headers: {
                        "X-Next-Token": components["headers"]["XNextToken"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TemplateWithBuilds"];
                    };
                };
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete template
         * @description Delete a template
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    templateID: components["parameters"]["templateID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The template was deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["401"];
                409: components["responses"]["409"];
                500: components["responses"]["500"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/templates/{templateID}/builds/{buildID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start template build (v2)
         * @description Start the build
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    templateID: components["parameters"]["templateID"];
                    buildID: components["parameters"]["buildID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TemplateBuildStartV2"];
                };
            };
            responses: {
                /** @description The build has started */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{templateID}/builds/{buildID}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Template build status
         * @description Get template build info
         */
        get: {
            parameters: {
                query?: {
                    /** @description Index of the starting log after level filtering */
                    logsOffset?: number;
                    limit?: number;
                    level?: components["schemas"]["LogLevel"];
                };
                header?: never;
                path: {
                    templateID: components["parameters"]["templateID"];
                    buildID: components["parameters"]["buildID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned the template */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TemplateBuildInfo"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{templateID}/builds/{buildID}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Template build logs
         * @description Get template build logs
         */
        get: {
            parameters: {
                query?: {
                    /** @description Inclusive starting timestamp in milliseconds */
                    cursor?: number;
                    limit?: number;
                    level?: components["schemas"]["LogLevel"];
                    direction?: components["schemas"]["LogsDirection"];
                    /** @description Source of the logs that should be returned from */
                    source?: components["schemas"]["LogsSource"];
                };
                header?: never;
                path: {
                    templateID: components["parameters"]["templateID"];
                    buildID: components["parameters"]["buildID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned the template build logs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TemplateBuildLogsResponse"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/aliases/{alias}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check template alias
         * @description Check if template with given alias exists
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    alias: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully queried template by alias */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TemplateAliasResponse"];
                    };
                };
                400: components["responses"]["400"];
                403: components["responses"]["403"];
                404: components["responses"]["404"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List nodes
         * @description List all nodes
         */
        get: {
            parameters: {
                query?: {
                    /** @description Identifier of the cluster */
                    clusterID?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned all nodes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Node"][];
                    };
                };
                401: components["responses"]["401"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{nodeID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Node info
         * @description Get node info
         */
        get: {
            parameters: {
                query?: {
                    /** @description Identifier of the cluster */
                    clusterID?: string;
                };
                header?: never;
                path: {
                    nodeID: components["parameters"]["nodeID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned the node */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NodeDetail"];
                    };
                };
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/volumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List team volumes
         * @description List team volumes
         */
        get: {
            parameters: {
                query?: {
                    /** @description Cursor to start the list from */
                    nextToken?: components["parameters"]["paginationNextToken"];
                    /** @description Maximum number of items to return per page */
                    limit?: components["parameters"]["paginationLimit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully listed team volumes */
                200: {
                    headers: {
                        "X-Next-Token": components["headers"]["XNextToken"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Volume"][];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        /**
         * Create team volume
         * @description Create a new team volume
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewVolume"];
                };
            };
            responses: {
                /** @description Successfully created a new team volume */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Volume"];
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                409: components["responses"]["409"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/volumes/{volumeID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Team volume
         * @description Get team volume info
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    volumeID: components["parameters"]["volumeID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully retrieved a team volume */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Volume"];
                    };
                };
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete team volume
         * @description Delete a team volume
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    volumeID: components["parameters"]["volumeID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully deleted a team volume */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                409: components["responses"]["409"];
                500: components["responses"]["500"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int32
         * @description CPU cores for the sandbox
         */
        CPUCount: number;
        /**
         * Format: int32
         * @description Memory for the sandbox in MiB
         */
        MemoryMB: number;
        /**
         * Format: int32
         * @description Disk size for the sandbox in MiB
         */
        DiskSizeMB: number;
        /** @description Version of the envd running in the sandbox */
        EnvdVersion: string;
        SandboxMetadata: {
            [key: string]: string;
        };
        /**
         * @description State of the sandbox
         * @enum {string}
         */
        SandboxState: "running" | "paused";
        /**
         * @description Sort direction
         * @default desc
         * @enum {string}
         */
        OrderDirection: "asc" | "desc";
        SnapshotInfo: {
            /** @description The actual snapshot ID (stable identifier). Always contains the raw snapshot UUID, never an alias. */
            snapshotID: string;
            /** @description User-provided aliases for the snapshot. Empty if no alias was assigned during snapshot creation. */
            names: string[];
            cpuCount: components["schemas"]["CPUCount"];
            memoryMB: components["schemas"]["MemoryMB"];
            diskSizeMB: components["schemas"]["DiskSizeMB"];
            /**
             * Format: date-time
             * @description Time when the snapshot was created
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Time when the snapshot was last updated
             */
            updatedAt: string;
            /** @description OverlayBD-native OCI image reference for the snapshot rootfs when source-registry image publication was enabled and succeeded. Omitted when no rootfs image was published. */
            imageRef?: string;
        };
        EnvVars: {
            [key: string]: string;
        };
        /** @description Source for a sandbox attached drive. `image` must be provided. */
        AttachedDriveSource: {
            /** @description OCI image reference to resolve into an OverlayBD drive. */
            image: string;
        };
        /** @description Block drive to attach when starting a sandbox. Attached drives are sandbox launch inputs; if the sandbox is later snapshotted, the current drive state is captured into the resulting snapshot. */
        AttachedDrive: {
            /** @description Identifier used for the attached Firecracker drive. Must be non-empty, unique per sandbox, and must not contain "/". */
            driveID: string;
            /**
             * @description Whether the attached drive should be mounted read-only. Defaults to true.
             * @default true
             */
            readOnly: boolean;
            /** @description Absolute guest mount path. Defaults to `/mnt/{driveID}`. Must not be `/`, contain `..`, spaces, commas, or colons, and must not be under reserved paths such as `/proc`, `/sys`, `/dev`, `/run`, `/agentenv`, or `/opt/agentenv`. */
            mountPath?: string;
            /** @description Optional sub-directory inside the drive to expose at `mountPath`, matching Kubernetes `volumeMounts.subPath`. When set, only the named sub-directory of the drive is visible at `mountPath` inside the guest. Must be a relative path, must not be empty, must not contain `..`, spaces, commas, or colons, and must not start with `/`. */
            subPath?: string;
            diskSizeMB?: components["schemas"]["DiskSizeMB"];
            source: components["schemas"]["AttachedDriveSource"];
        };
        /** @description Sandbox startup block drive declarations. */
        AttachedDrives: components["schemas"]["AttachedDrive"][];
        /** @description MCP configuration for the sandbox */
        Mcp: {
            [key: string]: unknown;
        } | null;
        /** @description Opaque JSON object interpreted only by the custom extension. An absent value and an empty object are equivalent: both mean empty params. */
        CustomExtensionParams: {
            [key: string]: unknown;
        };
        SandboxNetworkConfig: {
            /**
             * @description Specify if the sandbox URLs should be accessible only with authentication.
             * @default true
             */
            allowPublicTraffic: boolean;
            /** @description List of allowed destinations for egress traffic. Each entry can be a CIDR block (e.g. "8.8.8.8/32"), a bare IP address (e.g. "8.8.8.8"), or a domain name (e.g. "example.com", "*.example.com"). Allowed entries always take precedence over denied entries. */
            allowOut?: string[];
            /** @description List of denied CIDR blocks or IP addresses for egress traffic. Domain names are not supported for deny rules. */
            denyOut?: string[];
            /** @description Specify host mask which will be used for all sandbox requests */
            maskRequestHost?: string;
        };
        /** @description Network configuration update for a running sandbox. Replaces the current egress rules with the provided configuration. Omitting a field clears it. */
        SandboxNetworkUpdateConfig: {
            /** @description List of allowed destinations for egress traffic. Each entry can be a CIDR block (e.g. "8.8.8.8/32"), a bare IP address (e.g. "8.8.8.8"), or a domain name (e.g. "example.com", "*.example.com"). Allowed entries always take precedence over denied entries. */
            allowOut?: string[];
            /** @description List of denied CIDR blocks or IP addresses for egress traffic. Domain names are not supported for deny rules. */
            denyOut?: string[];
            /** @description Allow sandbox to access the internet. When set to false, it behaves the same as specifying denyOut to 0.0.0.0/0 in the network config. */
            allow_internet_access?: boolean;
        };
        /**
         * @description Auto-resume enabled flag for paused sandboxes. Default false.
         * @default false
         */
        SandboxAutoResumeEnabled: boolean;
        /** @description Auto-resume configuration for paused sandboxes. */
        SandboxAutoResumeConfig: {
            enabled: components["schemas"]["SandboxAutoResumeEnabled"];
        };
        /**
         * @description Action taken when the sandbox times out.
         * @enum {string}
         */
        SandboxOnTimeout: "kill" | "pause";
        /** @description Sandbox lifecycle policy returned by sandbox info. */
        SandboxLifecycle: {
            /** @description Whether the sandbox can auto-resume. */
            autoResume: boolean;
            onTimeout: components["schemas"]["SandboxOnTimeout"];
        };
        /** @description Metric entry with timestamp and line */
        SandboxMetric: {
            /**
             * Format: date-time
             * @deprecated
             * @description Timestamp of the metric entry
             */
            timestamp: string;
            /**
             * Format: int64
             * @description Timestamp of the metric entry in Unix time (seconds since epoch)
             */
            timestampUnix: number;
            /**
             * Format: int32
             * @description Number of CPU cores
             */
            cpuCount: number;
            /**
             * Format: float
             * @description CPU usage percentage
             */
            cpuUsedPct: number;
            /**
             * Format: int64
             * @description Memory used in bytes
             */
            memUsed: number;
            /**
             * Format: int64
             * @description Total memory in bytes
             */
            memTotal: number;
            /**
             * Format: int64
             * @description Cached memory (page cache) in bytes
             */
            memCache: number;
            /**
             * Format: int64
             * @description Disk used in bytes
             */
            diskUsed: number;
            /**
             * Format: int64
             * @description Total disk space in bytes
             */
            diskTotal: number;
        };
        SandboxVolumeMount: {
            /** @description Name of the volume */
            name: string;
            /** @description Path of the volume */
            path: string;
        };
        Sandbox: {
            /** @description Identifier of the template from which is the sandbox created */
            templateID: string;
            /** @description Identifier of the sandbox */
            sandboxID: string;
            /** @description Alias of the template */
            alias?: string;
            /**
             * @deprecated
             * @description Identifier of the client
             */
            clientID: string;
            envdVersion: components["schemas"]["EnvdVersion"];
            /** @description Access token used for envd communication */
            envdAccessToken?: string;
            /** @description Token required for accessing sandbox via proxy. */
            trafficAccessToken?: string | null;
            /** @description Base domain where the sandbox traffic is accessible */
            domain?: string | null;
        };
        SandboxDetail: {
            /** @description Identifier of the template from which is the sandbox created */
            templateID: string;
            /** @description Alias of the template */
            alias?: string;
            /** @description Identifier of the sandbox */
            sandboxID: string;
            /**
             * @deprecated
             * @description Identifier of the client
             */
            clientID: string;
            /**
             * Format: date-time
             * @description Time when the sandbox was started
             */
            startedAt: string;
            /**
             * Format: date-time
             * @description Time when the sandbox will expire
             */
            endAt: string;
            envdVersion: components["schemas"]["EnvdVersion"];
            /** @description Access token used for envd communication */
            envdAccessToken?: string;
            /** @description Whether internet access was explicitly enabled or disabled for the sandbox. Null means it was not explicitly set. */
            allowInternetAccess?: boolean | null;
            /** @description Base domain where the sandbox traffic is accessible */
            domain?: string | null;
            cpuCount: components["schemas"]["CPUCount"];
            memoryMB: components["schemas"]["MemoryMB"];
            diskSizeMB: components["schemas"]["DiskSizeMB"];
            metadata?: components["schemas"]["SandboxMetadata"];
            state: components["schemas"]["SandboxState"];
            network?: components["schemas"]["SandboxNetworkConfig"];
            lifecycle?: components["schemas"]["SandboxLifecycle"];
            volumeMounts?: components["schemas"]["SandboxVolumeMount"][];
        };
        ListedSandbox: {
            /** @description Identifier of the template from which is the sandbox created */
            templateID: string;
            /** @description Alias of the template */
            alias?: string;
            /** @description Identifier of the sandbox */
            sandboxID: string;
            /**
             * @deprecated
             * @description Identifier of the client
             */
            clientID: string;
            /**
             * Format: date-time
             * @description Time when the sandbox was started
             */
            startedAt: string;
            /**
             * Format: date-time
             * @description Time when the sandbox will expire
             */
            endAt: string;
            cpuCount: components["schemas"]["CPUCount"];
            memoryMB: components["schemas"]["MemoryMB"];
            diskSizeMB: components["schemas"]["DiskSizeMB"];
            metadata?: components["schemas"]["SandboxMetadata"];
            state: components["schemas"]["SandboxState"];
            envdVersion: components["schemas"]["EnvdVersion"];
            volumeMounts?: components["schemas"]["SandboxVolumeMount"][];
        };
        SandboxesWithMetrics: {
            sandboxes: {
                [key: string]: components["schemas"]["SandboxMetric"];
            };
        };
        NewSandbox: {
            /** @description Identifier of the required template/snapshot. Use POST /sandboxes-cold to create a sandbox directly from an external OCI image. */
            templateID: string;
            /**
             * Format: int32
             * @description Time to live for the sandbox in seconds.
             * @default 15
             */
            timeout: number;
            /**
             * @description Automatically pauses the sandbox after the timeout
             * @default true
             */
            autoPause: boolean;
            autoResume?: components["schemas"]["SandboxAutoResumeConfig"];
            /** @description Secure all system communication with sandbox */
            secure?: boolean;
            /** @description Allow sandbox to access the internet. When set to false, it behaves the same as specifying denyOut to 0.0.0.0/0 in the network config. */
            allow_internet_access?: boolean;
            network?: components["schemas"]["SandboxNetworkConfig"];
            metadata?: components["schemas"]["SandboxMetadata"];
            envVars?: components["schemas"]["EnvVars"];
            customExtensionParams?: components["schemas"]["CustomExtensionParams"];
            mcp?: components["schemas"]["Mcp"];
            volumeMounts?: components["schemas"]["SandboxVolumeMount"][];
        };
        /** @description Sandbox creation request. All system communication with the sandbox is always secured; the template's envd version must support secured access. */
        NewSandboxV2: {
            /** @description Identifier of the required template */
            templateID: string;
            /**
             * Format: int32
             * @description Time to live for the sandbox in seconds.
             * @default 300
             */
            timeout: number;
            /**
             * @description Automatically pauses the sandbox after the timeout
             * @default true
             */
            autoPause: boolean;
            autoResume?: components["schemas"]["SandboxAutoResumeConfig"];
            /** @description Allow sandbox to access the internet. When set to false, it behaves the same as specifying denyOut to 0.0.0.0/0 in the network config. */
            allow_internet_access?: boolean;
            network?: components["schemas"]["SandboxNetworkConfig"];
            metadata?: components["schemas"]["SandboxMetadata"];
            envVars?: components["schemas"]["EnvVars"];
            customExtensionParams?: components["schemas"]["CustomExtensionParams"];
            mcp?: components["schemas"]["Mcp"];
            volumeMounts?: components["schemas"]["SandboxVolumeMount"][];
        };
        ResumedSandbox: {
            /**
             * Format: int32
             * @description Time to live for the sandbox in seconds.
             * @default 15
             */
            timeout: number;
        };
        NewColdSandbox: {
            /** @description Explicit external OCI image reference to use as the sandbox rootfs. Cold starts may pull and convert OCI layers on a cache miss and can take tens of seconds. */
            image: string;
            /**
             * Format: int32
             * @description Time to live for the sandbox in seconds.
             * @default 15
             */
            timeout: number;
            /**
             * @description Automatically pauses the sandbox after the timeout
             * @default true
             */
            autoPause: boolean;
            autoResume?: components["schemas"]["SandboxAutoResumeConfig"];
            /** @description Secure all system communication with sandbox */
            secure?: boolean;
            /** @description Allow sandbox to access the internet. When set to false, it behaves the same as specifying denyOut to 0.0.0.0/0 in the network config. */
            allowInternetAccess?: boolean;
            network?: components["schemas"]["SandboxNetworkConfig"];
            metadata?: components["schemas"]["SandboxMetadata"];
            envVars?: components["schemas"]["EnvVars"];
            customExtensionParams?: components["schemas"]["CustomExtensionParams"];
            volumeMounts?: components["schemas"]["SandboxVolumeMount"][];
            /** @description CPU cores for the cold-start sandbox. */
            cpuCount?: components["schemas"]["CPUCount"];
            /** @description Memory for the cold-start sandbox in MiB. */
            memoryMB?: components["schemas"]["MemoryMB"];
            diskSizeMB?: components["schemas"]["DiskSizeMB"];
            /** @description Attached drives for the cold-start sandbox. If the sandbox is later snapshotted, current drive state is captured into the snapshot. */
            attachedDrives?: components["schemas"]["AttachedDrives"];
            /** @description Additional kernel command-line arguments appended to the Firecracker boot args for this cold-start sandbox. Arguments are whitespace-separated and may contain only 0-9, a-z, A-Z, underscore, hyphen, dot, slash, plus, or equals sign, so base64 values are allowed. The server also applies the firecracker.allowed_extra_boot_args_prefixes allowlist; non-matching or invalid arguments are silently ignored. */
            extraBootArgs?: string;
        };
        ConnectSandbox: {
            /**
             * Format: int32
             * @description Timeout in seconds from the current time after which the sandbox should expire
             */
            timeout: number;
        };
        ConnectSandboxV2: {
            /**
             * Format: int32
             * @description Timeout in seconds from the current time after which the sandbox should expire
             * @default 300
             */
            timeout: number;
        };
        SandboxTimeoutRequest: {
            /**
             * Format: int32
             * @description Timeout in seconds from the current time after which the sandbox should expire
             */
            timeout: number;
        };
        SandboxRefreshRequest: {
            /** @description Duration for which the sandbox should be kept alive in seconds */
            duration?: number;
        };
        SandboxSnapshotRequest: {
            /** @description Optional name for the snapshot template. If a snapshot template with this name already exists, a new build will be assigned to the existing template instead of creating a new one. */
            name?: string;
        };
        SandboxForkRequest: {
            /**
             * Format: int32
             * @description Time to live for the new forked sandboxes in seconds. When omitted, each fork inherits the source sandbox timeout.
             */
            timeout?: number;
            /**
             * Format: int32
             * @description Number of forked sandboxes to create. All forks boot from the same snapshot, so the snapshot is captured once regardless of count. Each fork succeeds or fails independently; the outcome of each is reported in its entry of the response list.
             * @default 1
             */
            count: number;
        };
        /** @description Result of one requested fork. Exactly one of sandbox or error is set: sandbox when the fork started successfully, error when it failed to start. */
        SandboxForkResult: {
            sandbox?: components["schemas"]["Sandbox"];
            error?: components["schemas"]["Error"];
        };
        Template: {
            /** @description Identifier of the template */
            templateID: string;
            /** @description Identifier of the last successful build for given template */
            buildID: string;
            cpuCount: components["schemas"]["CPUCount"];
            memoryMB: components["schemas"]["MemoryMB"];
            diskSizeMB: components["schemas"]["DiskSizeMB"];
            /** @description Whether the template is public or only accessible by the team */
            public: boolean;
            /** @description Names of the template (namespace/alias format when namespaced) */
            names: string[];
            /**
             * Format: date-time
             * @description Time when the template was created
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Time when the template was last updated
             */
            updatedAt: string;
            /**
             * Format: date-time
             * @description Time when the template was last used
             */
            lastSpawnedAt: string | null;
            /**
             * Format: int64
             * @description Number of times the template was used
             */
            spawnCount: number;
            /**
             * Format: int32
             * @description Number of times the template was built
             */
            buildCount: number;
            envdVersion: components["schemas"]["EnvdVersion"];
            buildStatus: components["schemas"]["TemplateBuildStatus"];
        };
        TemplateRequestResponseV3: {
            /** @description Identifier of the template */
            templateID: string;
            /** @description Identifier of the last successful build for given template */
            buildID: string;
            /** @description Whether the template is public or only accessible by the team */
            public: boolean;
            /** @description Names of the template */
            names: string[];
            /** @description Tags assigned to the template build */
            tags: string[];
            /**
             * @deprecated
             * @description Aliases of the template
             */
            aliases: string[];
        };
        TemplateBuild: {
            /**
             * Format: uuid
             * @description Identifier of the build
             */
            buildID: string;
            status: components["schemas"]["TemplateBuildStatus"];
            /**
             * Format: date-time
             * @description Time when the build was created
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Time when the build was last updated
             */
            updatedAt: string;
            /**
             * Format: date-time
             * @description Time when the build was finished
             */
            finishedAt?: string;
            cpuCount: components["schemas"]["CPUCount"];
            memoryMB: components["schemas"]["MemoryMB"];
            diskSizeMB?: components["schemas"]["DiskSizeMB"];
            envdVersion?: components["schemas"]["EnvdVersion"];
        };
        TemplateWithBuilds: {
            /** @description Identifier of the template */
            templateID: string;
            /** @description Whether the template is public or only accessible by the team */
            public: boolean;
            /** @description Names of the template (namespace/alias format when namespaced) */
            names: string[];
            /**
             * Format: date-time
             * @description Time when the template was created
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Time when the template was last updated
             */
            updatedAt: string;
            /**
             * Format: date-time
             * @description Time when the template was last used
             */
            lastSpawnedAt: string | null;
            /**
             * Format: int64
             * @description Number of times the template was used
             */
            spawnCount: number;
            /** @description List of builds for the template */
            builds: components["schemas"]["TemplateBuild"][];
        };
        TemplateAliasResponse: {
            /** @description Identifier of the template */
            templateID: string;
            /** @description Whether the template is public or only accessible by the team */
            public: boolean;
        };
        /** @description Step in the template build process */
        TemplateStep: {
            /** @description Type of the step */
            type: string;
            /**
             * @description Arguments for the step
             * @default []
             */
            args: string[];
            /** @description Hash of the files used in the step */
            filesHash?: string;
            /**
             * @description Whether the step should be forced to run regardless of the cache
             * @default false
             */
            force: boolean;
        };
        TemplateBuildRequestV3: {
            /** @description Name of the template. Can include a tag with colon separator (e.g. "my-template" or "my-template:v1"). If tag is included, it will be treated as if the tag was provided in the tags array. */
            name?: string;
            /** @description Tags to assign to the template build */
            tags?: string[];
            cpuCount?: components["schemas"]["CPUCount"];
            memoryMB?: components["schemas"]["MemoryMB"];
        };
        TemplateBuilderRequest: {
            /** @description Override the final image ENTRYPOINT/CMD for template startup. Omit to use the image command; an empty string disables startup. */
            startCmd?: string;
            /** @description Override the final image HEALTHCHECK before snapshot capture. */
            readyCmd?: string;
            /**
             * Format: uint32
             * @description Builder preparation and Dockerfile build deadline in seconds; defaults to 3600.
             */
            timeout?: number;
        };
        TemplateBuilder: {
            /** @description Required BuildKit image exporter name for this build. The server observes its successful completion and automatically imports and publishes the template. */
            imageName: string;
        };
        TemplateBuildStartV2: {
            /** @description Image to use as a base for the template build */
            fromImage?: string;
            /** @description Template to use as a base for the template build */
            fromTemplate?: string;
            /**
             * @description Whether the whole build should be forced to run regardless of the cache
             * @default false
             */
            force: boolean;
            /**
             * @description List of steps to execute in the template build
             * @default []
             */
            steps: components["schemas"]["TemplateStep"][];
            /** @description Start command to execute in the template after the build */
            startCmd?: string;
            /** @description Ready check command to execute in the template after the build */
            readyCmd?: string;
        };
        /**
         * @description State of the sandbox
         * @enum {string}
         */
        LogLevel: "debug" | "info" | "warn" | "error";
        BuildLogEntry: {
            /**
             * Format: date-time
             * @description Timestamp of the log entry
             */
            timestamp: string;
            /** @description Log message content */
            message: string;
            level: components["schemas"]["LogLevel"];
            /** @description Step in the build process related to the log entry */
            step?: string;
        };
        BuildStatusReason: {
            /** @description Message with the status reason, currently reporting only for error status */
            message: string;
            /** @description Step that failed */
            step?: string;
            /**
             * @description Log entries related to the status reason
             * @default []
             */
            logEntries: components["schemas"]["BuildLogEntry"][];
        };
        /**
         * @description Status of the template build
         * @enum {string}
         */
        TemplateBuildStatus: "building" | "waiting" | "ready" | "error";
        TemplateBuildInfo: {
            /**
             * @deprecated
             * @description Deprecated; always empty, use logEntries
             * @default []
             */
            logs: string[];
            /**
             * @description Build logs structured
             * @default []
             */
            logEntries: components["schemas"]["BuildLogEntry"][];
            /** @description Identifier of the template */
            templateID: string;
            /** @description Identifier of the build */
            buildID: string;
            status: components["schemas"]["TemplateBuildStatus"];
            reason?: components["schemas"]["BuildStatusReason"];
        };
        TemplateBuildLogsResponse: {
            /**
             * @description Build logs structured
             * @default []
             */
            logs: components["schemas"]["BuildLogEntry"][];
        };
        /**
         * @description Direction of the logs that should be returned
         * @enum {string}
         */
        LogsDirection: "forward" | "backward";
        /**
         * @description Source of the logs that should be returned
         * @enum {string}
         */
        LogsSource: "temporary" | "persistent";
        /**
         * @description Status of the node.
         *     - draining: the node is bound to be shut down. It will not accept new sandboxes and will stop once all existing sandboxes are done.
         * @enum {string}
         */
        NodeStatus: "ready" | "draining" | "connecting" | "unhealthy";
        DiskMetrics: {
            /** @description Mount point of the disk */
            mountPoint: string;
            /** @description Device name */
            device: string;
            /** @description Filesystem type (e.g., ext4, xfs) */
            filesystemType: string;
            /**
             * Format: uint64
             * @description Used space in bytes
             */
            usedBytes: number;
            /**
             * Format: uint64
             * @description Total space in bytes
             */
            totalBytes: number;
        };
        /** @description Node metrics */
        NodeMetrics: {
            /**
             * Format: uint32
             * @description Number of allocated CPU cores for the active running sandboxes (excludes paused)
             */
            allocatedCPU: number;
            /**
             * Format: uint32
             * @description Node CPU usage percentage
             */
            cpuPercent: number;
            /**
             * Format: uint32
             * @description Total number of CPU cores on the node
             */
            cpuCount: number;
            /**
             * Format: uint64
             * @description Amount of allocated memory in bytes for the active running sandboxes (excludes paused)
             */
            allocatedMemoryBytes: number;
            /**
             * Format: uint64
             * @description Node memory used in bytes
             */
            memoryUsedBytes: number;
            /**
             * Format: uint64
             * @description Total node memory in bytes
             */
            memoryTotalBytes: number;
            /** @description Detailed metrics for each disk/mount point */
            disks: components["schemas"]["DiskMetrics"][];
            /**
             * Format: uint32
             * @description Sum of CPU reservations across all sandboxes currently in the Paused state
             */
            pausedAllocatedCPU: number;
            /**
             * Format: uint64
             * @description Sum of memory reservations (bytes) across all sandboxes currently in the Paused state
             */
            pausedAllocatedMemoryBytes: number;
        };
        MachineInfo: {
            /** @description CPU family of the node */
            cpuFamily: string;
            /** @description CPU model of the node */
            cpuModel: string;
            /** @description CPU model name of the node */
            cpuModelName: string;
            /** @description CPU architecture of the node */
            cpuArchitecture: string;
        };
        Node: {
            /** @description Version of the orchestrator */
            version: string;
            /** @description Commit of the orchestrator */
            commit: string;
            /** @description Identifier of the node */
            id: string;
            /** @description Service instance identifier of the node */
            serviceInstanceID: string;
            /** @description Identifier of the cluster */
            clusterID: string;
            machineInfo: components["schemas"]["MachineInfo"];
            status: components["schemas"]["NodeStatus"];
            /**
             * Format: uint32
             * @description Number of sandboxes running on the node
             */
            sandboxCount: number;
            metrics: components["schemas"]["NodeMetrics"];
            /**
             * Format: uint64
             * @description Number of sandbox create successes
             */
            createSuccesses: number;
            /**
             * Format: uint64
             * @description Number of sandbox create fails
             */
            createFails: number;
            /**
             * Format: uint32
             * @description Number of starting Sandboxes
             */
            sandboxStartingCount: number;
            /**
             * Format: uint32
             * @description Number of sandboxes currently in the Paused state
             */
            sandboxPausedCount: number;
        };
        NodeDetail: {
            /** @description Identifier of the cluster */
            clusterID: string;
            /** @description Version of the orchestrator */
            version: string;
            /** @description Commit of the orchestrator */
            commit: string;
            /** @description Identifier of the node */
            id: string;
            /** @description Service instance identifier of the node */
            serviceInstanceID: string;
            machineInfo: components["schemas"]["MachineInfo"];
            status: components["schemas"]["NodeStatus"];
            /**
             * Format: uint32
             * @description Number of sandboxes running on the node
             */
            sandboxCount: number;
            metrics: components["schemas"]["NodeMetrics"];
            /**
             * Format: uint64
             * @description Number of sandbox create successes
             */
            createSuccesses: number;
            /**
             * Format: uint64
             * @description Number of sandbox create fails
             */
            createFails: number;
            /**
             * Format: uint32
             * @description Number of sandboxes currently in the Paused state
             */
            sandboxPausedCount: number;
        };
        Error: {
            /**
             * Format: int32
             * @description Error code
             */
            code: number;
            /** @description Error */
            message: string;
        };
        Volume: {
            /** @description ID of the volume */
            volumeID: string;
            /** @description Name of the volume */
            name: string;
            /** @description Access mode (`ro` or `exclusive`). */
            mode: string;
            /**
             * Format: int64
             * @description Effective volume size in MiB.
             */
            sizeMB: number;
            /** @description Availability state (`ready`, `uploading`, or `failed`). */
            status: string;
        };
        NewVolume: {
            /** @description Name of the volume */
            name: string;
            /**
             * Format: int64
             * @description Volume size in MiB. Defaults to 65536 MiB (64 GiB).
             * @default 65536
             */
            sizeMB: number;
            /** @description Access mode (`ro` or `exclusive`). */
            mode?: string;
            /** @description Existing volume ID or name to use as a COW source. An exclusive source must not be mounted by a sandbox; sandbox fork snapshots and publishes its owned volumes internally before creating child volumes. */
            fromVolume?: string;
            /** @description OCI or OverlayBD image reference for the initial content. */
            image?: string;
        };
    };
    responses: {
        /** @description Bad request */
        400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication error */
        401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Forbidden */
        403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflict */
        409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Server error */
        500: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        templateID: string;
        buildID: string;
        sandboxID: string;
        teamID: string;
        nodeID: string;
        apiKeyID: string;
        snapshotID: string;
        tag: string;
        /** @description Maximum number of items to return per page */
        paginationLimit: number;
        /** @description Cursor to start the list from */
        paginationNextToken: string;
        volumeID: string;
    };
    requestBodies: never;
    headers: {
        /** @description Cursor to fetch the next page of results, if more exist */
        XNextToken: string;
        /** @description Number of running sandboxes matching the filters, before pagination is applied. Only present when running sandboxes were requested. */
        XTotalRunning: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
